### ISSUE TITLE
BROKEN LINK: GitHub pull request documentation

### ISSUE THREAD

**Issue by knepprath** [Nike-Inc/cerberus#221]
When reading through the Cerberus docs I noticed that https://help.github.com/send-pull-requests/ is a broken link

cerberus/docs/contributing/how-to-contribute.md -> Additional Resources -> GitHub pull request documentation -> https://help.github.com/send-pull-requests/

**Comment by tunderwood** [comment]
Link has been fixed in commit 1d2d760.
